version: "3.4"
services:
    hangfire-workflow:
        container_name: hangfire-workflow
        build:
            context: .
            dockerfile: ./.devcontainer/Dockerfile
        volumes:
            # Update this to wherever you want VS Code to mount the folder of your project
            - .:/workspace
            # Forwards the local Docker socket to the container.
            - /var/run/docker.sock:/var/run/docker.sock
            # mount aws credentials to container
            - ~/.aws/:/root/.aws/
            # make sure to mount persistent directories for the node_modules,
            # this makes sure we don't copy osX files into the linux distro

            - bash-history:/root/.bash_history
            - extensions:/root/.vscode-server/extensions
            - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets
        # Overrides default command so things don't shut down after the process ends.
        command: sleep infinity
        networks:
            - app-network

volumes:
    bash-history:
    extensions:

networks:
    app-network:
        external:
            name: hf-bus_app-network
